project:
  type: book
  output-dir: docs

book:
  title: "DSAN Handbook"
  author: "DSAN Staff"
  chapters:
    - index.qmd
    - bootcamp/index.qmd
    - part: courses/index.qmd
      chapters:
        - courses/dsan5000.qmd
        - courses/dsan5100.qmd
        - courses/dsan5200.qmd
        - courses/dsan5450.qmd
        - courses/dsan5500.qmd
    - part: logistics/index.qmd
      chapters:
        - logistics/graduation.qmd
        - logistics/international.qmd
        - logistics/mentors.qmd
        - logistics/committees.qmd
        - logistics/resources.qmd
        - logistics/housing-transportation.qmd
        - logistics/taships-internships.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      text: "<script src='https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js'></script><script src='/sidebar-custom.js'></script>"
