# Student Committees

## Student Events & Social Committee

This committee is comprised of a Social Chair and 5-76 committee members. Students work closely with our Communications & Events Coordinator to foster a strong sense of community and support within our program by hosting social and professional events, developing shared community spaces, providing more opportunities to connect with each other, and sharing feedback from the student body. foster a strong sense of community, support DSAN program events, assist with brainstorming new possibilities for events, and provide feedback from the student body. When needed, committee members may assist with social media content creation.

## Student Academic & Curriculum Committee

This committee is comprised of 2-3 first-year and 2-3 second-year student representatives. Representatives serve as liaisons between students and DSAN faculty & leadership. They are expected to be available to the DSAN student body to gather feedback about classes, and work with DSAN leadership to address concerns and implement suggestions.

https://analytics.georgetown.edu/dsan-student-committees/

You can apply to join these committees in early Fall!