# Applying to Graduate: Process & Deadlines

Information about Commencement, caps and gowns, diplomas, etc.: https://grad.georgetown.edu/academics/current-students/#graduation-information

## Graduating in December:

You must apply to graduate via MyAccess by no later than December 1. Please review the information and instructions here: https://grad.georgetown.edu/academics/how-to-graduate/

When you apply to graduate, you will receive occasional updates from Graduate Student Services regarding degree posting, diplomas, etc.

There is only one commencement ceremony each year, and that is in May (usually the third Friday of May). You are more than welcome to return to Georgetown in May to participate in the ceremony!

## Graduating in May:

You MUST apply to graduate NO LATER THAN FEBRUARY 1 if you wish to have your name and graduation information printed in the Commencement Book.

If you miss the February 1 deadline, you may still apply to graduate until May 1. However, your name and graduation information will not appear in the Commencement Book.

Directions on how to apply to graduate can be found here: http://grad.georgetown.edu/academics/how-to-graduate/. Please select May 31 as your graduation date.

When you apply to graduate, you will receive occasional updates from Graduate Student Services regarding the ceremony, degree posting, diplomas, etc.

## Graduating in August:

You must apply to graduate via MyAccess by no later than August 1. Please review the information and instructions here: https://grad.georgetown.edu/academics/how-to-graduate/

When you apply to graduate, you will receive occasional updates from Graduate Student Services regarding degree posting, diplomas, etc.
