# Housing and Transportation

## Housing

The Graduate School of Arts & Sciences is pleased to offer graduate student housing at a brand new apartment residence located at 55 H Street NW.
Learn more here: https://grad.georgetown.edu/grad_housing/grad-housing-faqs/
In addition, the Office of Neighborhood Life is an excellent resource for off-campus options, particularly this page. There is also a wealth of housing and student life information on the Graduate School of Arts & Science's website.
Most graduate students at Georgetown University live near the campus, either in VA or MD. Many students choose to live in VA just across the Key Bridge so that they can walk across the bridge to class. Others live in MD and take the Metro to the Dupont Circle Bus station. The bus comes right to the campus. See the section below on transportation for more detail. Here is a Google map for reference: [Georgetown Area
](https://www.google.com/maps/@38.9094354,-77.0689275,14z)Georgetown University is in the middle of the map. Arlington, VA is south of the river. Many graduate students rent space in houses as a group. You can also look for places using web resources such as Georgetown Off-Campus Housing Service (https://ochlistings.georgetown.edu) or Apartment Finder (https://www.apartmentfinder.com/)
We have several first-year and second-year students who represent our program as Student Ambassadors. If you'd like a student's perspective/advice on housing options (or anything else!), please email our Ambassadors at gradanalytics@georgetown.edu.


## Transportation

You can get to campus by car, bus/shuttle or bike/on foot. Parking in Georgetown is limited by day and time and also does not extend for more than 2 hours. Maps of bus lines serving Georgetown are at https://www.wmata.com/schedules/maps/
There is no Metro (subway) stop in Georgetown, but the university provides a free shuttle service (GUTS) that has pick-up and drop-off from the DUPONT and ROSSLYN Metro stations. Information about GUTS is at http://otm.georgetown.edu/guts
Washington is great for bicycling and walking. Maps of bicycle friendly routes are at http://www.waba.org/resources/maps-and-documents/. There is also a good bicycle sharing system http://www.capitalbikeshare.com and electric scooter sharing at https://www.li.me/.

The Gym, The Library, and Graduate Student Study Areas
Yates Field House (the gym)
Georgetown University Library
Graduate Student Spaces