# International Students

## ANLY905 and CPT

If you are an international student(and not graduating in May 2022), you MUST be approved for CPT (Curricular Practical Training) in order to do an internship, and you MUST register for ANLY 905.

Please review the CPT information on the Office of Global Services website: https://internationalservices.georgetown.edu/students/employment/cpt

Please also review the entire CPT and internship process on our program website. Go to the International Student Resources page and scroll down to the link "Internship Information for International Students." When you read it you will see that our program requires you to submit a Google Form as part of the CPT process. Please thoroughly review the Google Form and follow the instructions for uploading your CPT form to Google Drive (be sure to email Dir.Heather Connor once you have done so).


More Info about CPT:

 You can view the CPT module video (Links to an external site.) and video transcript (Links to an external site.) in Box.
The module also links to the following resources mentioned in the video:
CPT eligible course list (Links to an external site.)
CPT application instructions (Links to an external site.)
Career Resources for International Students (Links to an external site.)
Research a company for a job interview (Links to an external site.)
Wilberforce Pamphlet

Requirements
1. You need to read the attached pdf carefully.
2. Complete & Submit the DSAN CPT Request Form.
This is the DSAN CPT Request Form, which is the first step of the process: https://forms.gle/ZAVVn6c3T1TFTk5w6
3.  Complete the CPT Canvas module quiz (this you will be able to see in your Canvas and is different from ANLY905)and complete the CPT Form (CPT Request Form (Public) (1).pdf) , and all related steps, thoroughly.
 4. You are required to submit a 10 page paper. 
5.  Internships must begin between the first day of classes and the last day of add/drop, and must end between the last day of classes and the end of final exams.