# Electronic Resources (NetID, Email, Canvas)

You already have a Georgetown University network identification, NetID. It is your initials followed by a few digits. Please refer to your admissions letter for your NetID, temporary password, and instructions for activating your NetID**.**
Your NetID also defines your Georgetown email address. For example, if your NetID is abc278, also your Georgetown email address will be abc278@georgetown.edu.
Always and continuously check your Georgetown email! Check it every day starting now and ending after you graduate.
Your NetID will also grant you access to Georgetown systems – such as MyAccess and Canvas.
While you are on campus, you will be able to access the wireless network using your NetID.
CANVAS

Canvas is a course management system that your instructors will be using for your course grades and other course interaction. You can access Canvas using your NetID and password from a web browser or via the app for smartphones and tablets.
Other electronic services for you to explore are at https://uis.georgetown.edu/new-to-georgetown/ and http://www.library.georgetown.edu.
GO CARDS

The GOCard is the official identification card of Georgetown University. It can also be used to make purchases on and off campus, as well as allowing you access to campus buildings and the gym. You must submit your photo prior to arriving on campus. Please visit the GOCard website for instructions on securing your GOCard.
