# TA, Internship, and Job Opportunities

## Being a Teaching Assistant (TA)

Being a TA is a great experience. We often have many TA opportunities and these will only increase over time.
We encourage first-term students to focus 100% on coursework and limit working as much as possible. Because first-term students should focus on coursework, TA positions are prioritized for second-term and second-year students. However, first-term students are eligible to apply. You will receive an email during the summer with information about the Fall TA application process.

## Working and Internships

I strongly encourage students to take up internships during their study period. This experience can be immensely valuable and help you with finding jobs in the future. However, it is important to note that our program is rigorous and demands significant commitment and effort. Therefore, it is crucial to manage your time efficiently and effectively. To this end, I recommend considering summer internships, as they can provide a valuable opportunity to gain practical experience while managing your time effectively.

Domestic students may work as they wish.
International students may choose to take internships via the DSAN 5925/CPT option.
We will discuss this in great detail during the August workshop. International students may start accepting internships by Summer of 2024. No internships are permitted for Fall 2023 or Spring 2024. **Please note that this is international and domestic law (not our rules) so we cannot waive or change this policy.
We encourage all students to participate in summer internships. There are special rules for international students. We will hold a workshop in August and will send out a separate email for understanding and getting internships for all students.